In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import ipywidgets 
from ipywidgets import interact, interactive,fixed,interact_manual
import matplotlib.cm as cm

In [3]:
# read the data as ufos, and make the new column name for the data
ufos= pd.read_csv('/Users/dannyqiu/Desktop/UIUC/IS445/Week4/ufo-scrubbed-geocoded-time-standardized-00.csv',
                     names=["date", "city", "state", "country","shape", "duration_seconds", "duration","comment", "report_date", "latitude", "longitude"],
                     parse_dates =['date','report_date'])

In [4]:
#set the unusal to unknown
ufos=ufos.fillna({'country':'unknown','state':'unknown','shape':'unknown'})

In [5]:
# Since the sample was too big, so we downsample the data to 1000 and
#rename as ufosDS
nsample=1000
downsampleInds =np.random.choice(range(len(ufos)-1),nsample,replace=False)
ufosDS=ufos.loc[downsampleInds]

In [6]:
#I want to make statistics about the date of year and date of month.
# and I set up as new columns in table
ufosDS['year']=ufosDS['date'].dt.year
ufosDS['month']=ufosDS['date'].dt.month
ufosDS

,date,city,state,country,shape,duration_seconds,duration,comment,report_date,latitude,longitude,year,month
35533,2008-03-09 19:48:00,evansville,in,us,light,3.0,2-3 seconds,I was driving south on a back road off of High...,2008-03-31,37.974722,-87.555833,2008,3
67366,1987-08-18 22:00:00,lincoln (near),il,us,disk,30.0,20-30 seconds,I saw something in a cornfield very close to t...,1999-08-10,40.148333,-89.364722,1987,8
11274,2012-01-01 00:11:00,lake stevens,wa,us,light,300.0,5 minutes,Red light flew up quickly&#44hovered&#44moved ...,2012-01-24,48.015278,-122.062500,2012,1
38073,2014-04-20 22:50:00,seattle,wa,us,formation,5.0,5 seconds,I witnessed two lights in formation moving in ...,2014-04-24,47.606389,-122.330833,2014,4
63732,2002-07-08 21:10:00,pembroke pines,fl,us,unknown,10.0,10 seconds,Glowing Green Orb shot across the sky.,2007-02-24,26.002778,-80.224167,2002,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14441,2006-11-04 21:20:00,bloomington,ca,us,light,3.0,3 seconds,While driving home in Bloomington&#44 we turne...,2006-12-07,34.070278,-117.395000,2006,11
15572,2001-11-07 00:00:00,west columbia,tx,unknown,fireball,2.0,2 seconds,Green Fireball,2004-11-09,32.227821,-98.209051,2001,11
48271,2005-06-13 21:45:00,bertram,tx,us,oval,300.0,5 mins.,oval slow moving craft,2005-06-20,30.743611,-98.055278,2005,6
73532,2001-09-01 22:00:00,halifax (canada),ns,ca,fireball,2.0,seconds,A bright green fireball in the sky that lasted...,2009-01-10,44.650000,-63.600000,2001,9
16822,2012-01-20 20:30:00,daytona beach,fl,us,oval,300.0,5 minutes,6 red balls&#44 and each ball had a microsized...,2012-01-24,29.210556,-81.023056,2012,1

In [7]:
#got all the colormaps style as and save as color
color=plt.colormaps()

In [26]:
# using the ipywidgets to interact the table and make a drop down menus 
#that users can choose y-axis and x-axis aslo the colormap style.The colormap differnce is depend on the duration-seconds
@ipywidgets.interact(x=['country','month'],y=['shape','year'],colormap=color)
def make_plot(x,y,colormap):
    fig,ax=plt.subplots(1,1,figsize=(20,10))
    plt.scatter(ufosDS[x],ufosDS[y],c=np.log10(ufosDS['duration_seconds']),cmap=colormap)
    plt.title(x+' vs '+y,fontsize=40)
    plt.xlabel=x
    plt.ylable=y
    plt.show()

interactive(children=(Dropdown(description='x', options=('country', 'month'), value='country'), Dropdown(descrâ€¦

In [9]:
# set the bins number that we can use later
bins_number=[10,20,30,40,50,60,70,80,90,100]

In [25]:
# make ipywidgets that interatc with columns using histogram,
#make barplot for categorical variables, and make histogram for numerical variables
@ipywidgets.interact(x=['state','year'],Bins=bins_number)
def hist_plot(x,Bins):
    if x =='year':
        fig,ax=plt.subplots(1,1,figsize=(20,10))
        plt.hist(ufosDS[x],bins=Bins,edgecolor='black',linewidth=1.2)
        plt.title(x+' with '+str(Bins)+'bins',fontsize=40)
        plt.show()
    else:
        fig,ax=plt.subplots(1,1,figsize=(20,10))
        plt.bar(ufosDS[x],ufosDS['shape'],edgecolor='black',linewidth=1.2)
        plt.title(x+' vs'+' shape',fontsize=40)
        plt.show()

interactive(children=(Dropdown(description='x', options=('state', 'year'), value='state'), Dropdown(descriptioâ€¦